Update contributors.json
subeshb1/developer-community-stats pull request #58
Opened 2020-10-10 13:03 UTC by Swapnil074

## Issue 08

## Description

2020-10-10 13:06 UTC, subeshb1 commented on contributors.json
> +  "swpanil074": {
Let's keep this sorted in ascending  order by GitHub user name

2020-10-11 11:16 UTC, subeshb1 requested changes
Let's keep `contributors.json` sorted in ascending order by GitHub user name

2020-10-12 13:27 UTC, Swapnil074 commented
> Let's keep `contributors.json` sorted in ascending order by GitHub user name
just updated in the order

2020-10-12 14:08 UTC, subeshb1 commented on contributors.json
> +  },
```suggestion
  }
```

2020-10-12 14:08 UTC, subeshb1 commented on contributors.json
> +
```suggestion
```

2020-10-12 14:13 UTC, subeshb1 approved these changes

2020-10-12 14:13 UTC, merged